In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv("iris.csv")

In [5]:
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [6]:
df.shape

(150, 5)

In [8]:
x=df.iloc[:,:-1]
y=df.iloc[:,4]

In [9]:
df.iloc[:,:-1]

sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=101)

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler=StandardScaler()

In [15]:
scaler.fit(x_train)

StandardScaler()

In [16]:
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [24]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [18]:
y_predict=classifier.predict(x_test)

In [19]:
from sklearn.metrics import classification_report,confusion_matrix

In [20]:
print(classification_report(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        10
  Versicolor       0.92      1.00      0.96        12
   Virginica       1.00      0.88      0.93         8

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30

[[10  0  0]
 [ 0 12  0]
 [ 0  1  7]]


In [21]:
y_predict

array(['Setosa', 'Setosa', 'Setosa', 'Virginica', 'Versicolor',
       'Virginica', 'Versicolor', 'Versicolor', 'Virginica', 'Setosa',
       'Virginica', 'Setosa', 'Setosa', 'Virginica', 'Virginica',
       'Versicolor', 'Versicolor', 'Versicolor', 'Setosa', 'Versicolor',
       'Versicolor', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Virginica', 'Setosa', 'Setosa'],
      dtype=object)

In [22]:
x_test

array([[-4.26739366e-01,  2.72483973e+00, -1.34658875e+00,
        -1.30814890e+00],
       [-5.45829422e-01,  1.99713773e+00, -1.40259937e+00,
        -1.05248462e+00],
       [-1.02218964e+00,  1.02686839e+00, -1.23456750e+00,
        -7.96820339e-01],
       [ 1.59779158e+00, -1.85968290e-01,  1.11787870e+00,
         4.81501060e-01],
       [ 1.35961147e+00,  2.99166380e-01,  5.01761838e-01,
         2.25836781e-01],
       [ 5.25981079e-01, -9.13670296e-01,  6.13783085e-01,
         7.37165340e-01],
       [ 4.06891023e-01, -2.12650697e+00,  3.89740590e-01,
         3.53668920e-01],
       [-4.26739366e-01, -1.88393964e+00,  1.09687471e-01,
         9.80046406e-02],
       [ 5.25981079e-01, -1.39880497e+00,  6.69793709e-01,
         8.64997480e-01],
       [-1.14127970e+00, -1.85968290e-01, -1.34658875e+00,
        -1.30814890e+00],
       [ 7.64161190e-01, -1.85968290e-01,  7.81814956e-01,
         9.92829620e-01],
       [-7.84009533e-01,  2.48227240e+00, -1.29057812e+00,
      